import { gql } from "graphql-request";

export const GET_LOCATION_GROUP_JSON = gql`
  query GetExactGroup($uuid: ID) {
    group(id: $uuid) {
      edges {
        node {
          id
          uuid
          code
          jsonExt
          location {
            id
          }
          head {
            id
            uuid
            firstName
            lastName
          }
        }
      }
    }
  }
`;

export const TEST_JSON = {
  dob: "1983-12-27",
  first_name: "Christina",
  last_name: "Petro Mkuki",
  head: "Christina Petro Mkuki",
  hhrep: 1,
  head_id: "ce96d2a5-d263-4c8f-a993-f07ca541e2a7",
  pssn_wave: "1",
  group_code: "P3-130518103-59724107",
  consent_res: "1",
  external_id: "59-72-41-07",
  interview_key: "59-72-41-07",
  location_code: "130518103",
  location_name: "Minyughe",
  individual_role: "HEAD",
  primary_recipient: "Christina Petro Mkuki",
  individual_role_code: 1,
  primary_recipient_id: "ce96d2a5-d263-4c8f-a993-f07ca541e2a7",
  pmt_class: null,
  pmt_score: null,
  payment_account: {
    account_number: "0700000000",
    account_name: "Christina Petro Mkuki",
    provider_name: "VODACOM (M-PESA)",
    provider_type: "MOBILE_MONEY",
    is_verified: true,
    updated_at: "2026-03-25T18:50:00Z",
  },
  members: {
    "a72d2b9b-37b7-4d34-a2b2-c1017ec7b616": "Imelda Hamisi Hasani",
    "ce96d2a5-d263-4c8f-a993-f07ca541e2a7": "Christina Petro Mkuki",
  },
  raw: {
    age: "42",
    sex: "2",
    Id_No: "",
    Id_NIN: "",
    TF4_NO: "51",
    hh_rep: "1",
    college: "0",
    disease: "0",
    hh_size: "2",
    primary: "0",
    gps_accu: "-999999999",
    hh_photo: "hh_photo__.jpg",
    hhh_name: "Christina Petro Mkuki",
    phone_no2: "0700000000",
    secondary: "0",
    ward_code: "1305181",
    ward_name: "1305181",
    hh_bedroom: "2",
    mb_id_type: "12",
    rel_to_hhh: "1",
    sssys_irnd: "0.773094019281256",
    disaster__1: "0",
    disaster__2: "1",
    disaster__3: "0",
    disaster__4: "0",
    disaster__5: "0",
    disaster__6: "0",
    disaster__7: "0",
    disaster__8: "0",
    disaster__9: "0",
    has__errors: "0",
    hh_asset__1: "0",
    hh_asset__2: "0",
    hh_asset__3: "0",
    hh_asset__4: "0",
    hh_asset__5: "0",
    hh_asset__6: "0",
    hh_asset__7: "0",
    hh_asset__8: "1",
    hh_asset__9: "0",
    hh_location: "2",
    kindergaten: "0",
    phone_no_oz: "0700000000",
    region_code: "13",
    region_name: "Singida",
    disaster__10: "0",
    disaster__11: "0",
    disaster__12: "0",
    hh_asset__10: "0",
    hh_asset__11: "0",
    hh_asset__12: "0",
    hh_asset__13: "0",
    hh_asset__14: "0",
    hh_asset__15: "0",
    hh_asset__16: "0",
    hh_asset__17: "0",
    hh_asset__18: "0",
    hh_asset__19: "0",
    hh_asset__20: "0",
    hh_asset__21: "0",
    hh_asset__22: "0",
    hh_asset__23: "0",
    hh_asset__24: "0",
    hh_asset__25: "1",
    hh_asset__26: "0",
    hh_asset__27: "0",
    hh_asset__28: "0",
    hh_asset__29: "0",
    hh_asset__30: "0",
    hh_asset__31: "0",
    hh_mbrs_name: "Christina Petro Mkuki",
    hhroster__id: "1",
    memberlineno: "1",
    read_n_write: "1",
    village_code: "130518103",
    village_name: "130518103",
    with_kitchen: "2",
    district_code: "1305",
    district_name: "Ikungi DC",
    existing_hhid: "",
    hhh_Edu_level: "7",
    hunger_status: "2",
    interview__id: "6f720b8fa8e44e759d2f3cfc54967afe",
    not_in_school: "0",
    roof_material: "6",
    wall_material: "3",
    assignment__id: "354857",
    cooking_energy: "8",
    edu_sponser__1: "1",
    edu_sponser__2: "0",
    edu_sponser__3: "0",
    floor_material: "7",
    hh_mb_phone_No: "0792924497",
    house_owneship: "1",
    inschool_total: "1",
    interview_date: "2026-01-02T11:30:37",
    lighting_means: "4",
    disability_mute: "0",
    disease_type__1: "",
    disease_type__2: "",
    disease_type__3: "",
    disease_type__4: "",
    disease_type__5: "",
    disease_type__6: "",
    disease_type__7: "",
    disease_type__8: "",
    disease_type__9: "",
    hh_mbrs_name__0: "Christina Petro Mkuki",
    hh_mbrs_name__1: "Imelda Hamisi Hasani",
    hh_mbrs_name__2: "##N/A##",
    hh_mbrs_name__3: "##N/A##",
    hh_mbrs_name__4: "##N/A##",
    hh_mbrs_name__5: "##N/A##",
    hh_mbrs_name__6: "##N/A##",
    hh_mbrs_name__7: "##N/A##",
    hh_mbrs_name__8: "##N/A##",
    hh_mbrs_name__9: "##N/A##",
    number_of_rooms: "2",
    disease_type__10: "",
    disease_type__11: "",
    disease_type__12: "",
    disease_type__13: "",
    disease_type__14: "",
    disease_type__15: "",
    disease_type__94: "",
    health_insurance: "2",
    hh_mbrs_name__10: "##N/A##",
    hh_mbrs_name__11: "##N/A##",
    hh_mbrs_name__12: "##N/A##",
    hh_mbrs_name__13: "##N/A##",
    hh_mbrs_name__14: "##N/A##",
    hh_mbrs_name__15: "##N/A##",
    hh_mbrs_name__16: "##N/A##",
    hh_mbrs_name__17: "##N/A##",
    hh_mbrs_name__18: "##N/A##",
    hh_mbrs_name__19: "##N/A##",
    source_income__1: "1",
    source_income__2: "0",
    source_income__3: "0",
    source_income__4: "0",
    source_income__5: "0",
    source_income__6: "0",
    source_income__7: "0",
    source_income__8: "0",
    source_income__9: "0",
    disability_memory: "0",
    disability_visual: "0",
    disast_coping_oth: "",
    interview__status: "120",
    interview_results: "1",
    source_income__10: "0",
    disability_hearing: "0",
    rsn_not_attend_xll: "",
    disability_albinism: "0",
    disability_mobility: "0",
    disability_selfcare: "0",
    geo_codes__Accuracy: "11.199999809265137",
    geo_codes__Altitude: "1210.1",
    geo_codes__Latitude: "-4.974793333333333",
    disast_coping_act__1: "0",
    disast_coping_act__2: "0",
    disast_coping_act__3: "0",
    disast_coping_act__4: "1",
    disast_coping_act__5: "0",
    disast_coping_act__6: "0",
    geo_codes__Longitude: "34.54034",
    geo_codes__Timestamp: "2026-01-02T08:28:54",
    is_tasaf_beneficiary: "2",
    Interviewer_suggestions: "Nimepewa ushirikiano",
  },
};
