import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query GetRegionDistricts($regionId: ID) {\n    locations(type: \"R\", id: $regionId) {\n      edges {\n        node {\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetRegionDistrictsDocument,
    "\n  query GetRegionsWithDistricts {\n    locations(type: \"R\") {\n      edges {\n        node {\n          id\n          uuid\n          name\n          code\n          type\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetRegionsWithDistrictsDocument,
    "\n  query GetWardVillages($wardId: ID) {\n    locations(type: \"W\", id: $wardId) {\n      edges {\n        node {\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetWardVillagesDocument,
    "\n  query GetDistrictWards($districtId: ID) {\n    locations(type: \"D\", id: $districtId) {\n      edges {\n        node {\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n                children {\n                  edges {\n                    node {\n                      id\n                      uuid\n                      name\n                      code\n                      type\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetDistrictWardsDocument,
    "\n  mutation SyncPaymentAccount(\n    $accountProvider: String\n    $accountNumber: String\n    $accountName: String\n    $householdId: String\n    $clientMutationId: String\n  ) {\n    createTicket(\n      input: {\n        title: $accountProvider\n        category: \"PaymentAccount\"\n        description: $accountName\n        flags: $accountNumber\n        channel: $householdId\n        clientMutationId: $clientMutationId\n      }\n    ) {\n      internalId\n      clientMutationId\n    }\n  }\n": typeof types.SyncPaymentAccountDocument,
    "\n  mutation SyncHouseholdChange(\n    $title: String\n    $category: String!\n    $flags: String\n    $channel: String\n    $description: String\n    $clientMutationId: String\n  ) {\n    createTicket(\n      input: {\n        title: $title\n        category: $category\n        flags: $flags\n        channel: $channel\n        description: $description\n        clientMutationId: $clientMutationId\n      }\n    ) {\n      internalId\n      clientMutationId\n    }\n  }\n": typeof types.SyncHouseholdChangeDocument,
    "\n  mutation CreateAttendance(\n    $title: String\n    $category: String!\n    $priority: String\n    $incidentDate: Date\n    $flags: String\n    $channel: String\n    $description: String\n    $clientMutationId: String\n  ) {\n    createTicket(\n      input: {\n        title: $title\n        category: $category\n        priority: $priority\n        channel: $channel\n        dateOfIncident: $incidentDate\n        flags: $flags\n        description: $description\n        clientMutationId: $clientMutationId\n      }\n    ) {\n      internalId\n      clientMutationId\n    }\n  }\n": typeof types.CreateAttendanceDocument,
    "\n  query GetRegionDistrictsForField($regionId: ID) {\n    locations(type: \"R\", id: $regionId) {\n      edges {\n        node {\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetRegionDistrictsForFieldDocument,
    "\n  query GetRegionsWithDistrictsForField {\n    locations(type: \"R\") {\n      edges {\n        node {\n          id\n          uuid\n          name\n          code\n          type\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetRegionsWithDistrictsForFieldDocument,
    "\n  query GetWardVillagesForField($wardId: ID) {\n    locations(type: \"W\", id: $wardId) {\n      edges {\n        node {\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetWardVillagesForFieldDocument,
    "\n  query GetDistrictWardsForField($districtId: ID) {\n    locations(type: \"D\", id: $districtId) {\n      edges {\n        node {\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n                children {\n                  edges {\n                    node {\n                      id\n                      uuid\n                      name\n                      code\n                      type\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetDistrictWardsForFieldDocument,
    "\n  mutation CreateGrievance(\n    $title: String\n    $category: String!\n    $priority: String\n    $incidentDate: Date\n    $flags: String\n    $channel: String\n    $description: String\n    $clientMutationId: String\n  ) {\n    createTicket(\n      input: {\n        title: $title\n        category: $category\n        priority: $priority\n        channel: $channel\n        dateOfIncident: $incidentDate\n        flags: $flags\n        description: $description\n        clientMutationId: $clientMutationId\n      }\n    ) {\n      internalId\n      clientMutationId\n    }\n  }\n": typeof types.CreateGrievanceDocument,
    "\n  mutation SyncPwpSession(\n    $date: String\n    $notes: String\n    $villageId: String\n    $clientMutationId: String\n  ) {\n    createTicket(\n      input: {\n        title: $date\n        category: \"PWP\"\n        description: $notes\n        flags: $villageId\n        clientMutationId: $clientMutationId\n      }\n    ) {\n      internalId\n      clientMutationId\n    }\n  }\n": typeof types.SyncPwpSessionDocument,
    "\n  mutation Authenticate($username: String!, $password: String!) {\n    tokenAuth(username: $username, password: $password) {\n      token\n      refreshExpiresIn\n    }\n  }\n": typeof types.AuthenticateDocument,
    "\n  query GetCurrentUser {\n    user {\n      id\n      username\n      email\n      lastName\n      otherNames\n      phone\n      iUser {\n        id\n        language {\n          code\n          name\n        }\n      }\n    }\n  }\n": typeof types.GetCurrentUserDocument,
    "\n  query GetDistrictsSync($after: String, $first: Int!) {\n    locations(type: \"D\", after: $after, first: $first) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          uuid\n          name\n          code\n          parent {\n            id\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetDistrictsSyncDocument,
    "\n  query GetRegionsSync($after: String, $first: Int!) {\n    locations(type: \"R\", after: $after, first: $first) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          uuid\n          name\n          code\n        }\n      }\n    }\n  }\n": typeof types.GetRegionsSyncDocument,
    "\n  query GetLocationGroups($after: String, $first: Int, $villageId: String) {\n    group(\n      isDeleted: false\n      parentLocation: $villageId\n      parentLocationLevel: 3\n      first: $first\n      after: $after\n    ) {\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      edges {\n        node {\n          id\n          uuid\n          code\n          head {\n            firstName\n            lastName\n          }\n          jsonExt\n          groupindividuals(first: 50, isDeleted: false) {\n            edges {\n              node {\n                individual {\n                  uuid\n                  benefitconsumptionSet(first: 50, isDeleted: false) {\n                    edges {\n                      node {\n                        id\n                        uuid\n                        amount\n                        dateDue\n                        status\n                        type\n                        payrollbenefitconsumptionSet(first: 5, isDeleted: false) {\n                          edges {\n                            node {\n                              payroll {\n                                paymentCycle {\n                                  code\n                                  startDate\n                                  endDate\n                                }\n                              }\n                            }\n                          }\n                        }\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetLocationGroupsDocument,
    "\n  query GetVillagesSync($after: String, $first: Int!) {\n    locations(type: \"V\", after: $after, first: $first) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          uuid\n          name\n          code\n          parent {\n            id\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetVillagesSyncDocument,
    "\n  query GetWardsSync($after: String, $first: Int!) {\n    locations(type: \"W\", after: $after, first: $first) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          uuid\n          name\n          code\n          parent {\n            id\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetWardsSyncDocument,
};
const documents: Documents = {
    "\n  query GetRegionDistricts($regionId: ID) {\n    locations(type: \"R\", id: $regionId) {\n      edges {\n        node {\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetRegionDistrictsDocument,
    "\n  query GetRegionsWithDistricts {\n    locations(type: \"R\") {\n      edges {\n        node {\n          id\n          uuid\n          name\n          code\n          type\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetRegionsWithDistrictsDocument,
    "\n  query GetWardVillages($wardId: ID) {\n    locations(type: \"W\", id: $wardId) {\n      edges {\n        node {\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetWardVillagesDocument,
    "\n  query GetDistrictWards($districtId: ID) {\n    locations(type: \"D\", id: $districtId) {\n      edges {\n        node {\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n                children {\n                  edges {\n                    node {\n                      id\n                      uuid\n                      name\n                      code\n                      type\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetDistrictWardsDocument,
    "\n  mutation SyncPaymentAccount(\n    $accountProvider: String\n    $accountNumber: String\n    $accountName: String\n    $householdId: String\n    $clientMutationId: String\n  ) {\n    createTicket(\n      input: {\n        title: $accountProvider\n        category: \"PaymentAccount\"\n        description: $accountName\n        flags: $accountNumber\n        channel: $householdId\n        clientMutationId: $clientMutationId\n      }\n    ) {\n      internalId\n      clientMutationId\n    }\n  }\n": types.SyncPaymentAccountDocument,
    "\n  mutation SyncHouseholdChange(\n    $title: String\n    $category: String!\n    $flags: String\n    $channel: String\n    $description: String\n    $clientMutationId: String\n  ) {\n    createTicket(\n      input: {\n        title: $title\n        category: $category\n        flags: $flags\n        channel: $channel\n        description: $description\n        clientMutationId: $clientMutationId\n      }\n    ) {\n      internalId\n      clientMutationId\n    }\n  }\n": types.SyncHouseholdChangeDocument,
    "\n  mutation CreateAttendance(\n    $title: String\n    $category: String!\n    $priority: String\n    $incidentDate: Date\n    $flags: String\n    $channel: String\n    $description: String\n    $clientMutationId: String\n  ) {\n    createTicket(\n      input: {\n        title: $title\n        category: $category\n        priority: $priority\n        channel: $channel\n        dateOfIncident: $incidentDate\n        flags: $flags\n        description: $description\n        clientMutationId: $clientMutationId\n      }\n    ) {\n      internalId\n      clientMutationId\n    }\n  }\n": types.CreateAttendanceDocument,
    "\n  query GetRegionDistrictsForField($regionId: ID) {\n    locations(type: \"R\", id: $regionId) {\n      edges {\n        node {\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetRegionDistrictsForFieldDocument,
    "\n  query GetRegionsWithDistrictsForField {\n    locations(type: \"R\") {\n      edges {\n        node {\n          id\n          uuid\n          name\n          code\n          type\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetRegionsWithDistrictsForFieldDocument,
    "\n  query GetWardVillagesForField($wardId: ID) {\n    locations(type: \"W\", id: $wardId) {\n      edges {\n        node {\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetWardVillagesForFieldDocument,
    "\n  query GetDistrictWardsForField($districtId: ID) {\n    locations(type: \"D\", id: $districtId) {\n      edges {\n        node {\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n                children {\n                  edges {\n                    node {\n                      id\n                      uuid\n                      name\n                      code\n                      type\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetDistrictWardsForFieldDocument,
    "\n  mutation CreateGrievance(\n    $title: String\n    $category: String!\n    $priority: String\n    $incidentDate: Date\n    $flags: String\n    $channel: String\n    $description: String\n    $clientMutationId: String\n  ) {\n    createTicket(\n      input: {\n        title: $title\n        category: $category\n        priority: $priority\n        channel: $channel\n        dateOfIncident: $incidentDate\n        flags: $flags\n        description: $description\n        clientMutationId: $clientMutationId\n      }\n    ) {\n      internalId\n      clientMutationId\n    }\n  }\n": types.CreateGrievanceDocument,
    "\n  mutation SyncPwpSession(\n    $date: String\n    $notes: String\n    $villageId: String\n    $clientMutationId: String\n  ) {\n    createTicket(\n      input: {\n        title: $date\n        category: \"PWP\"\n        description: $notes\n        flags: $villageId\n        clientMutationId: $clientMutationId\n      }\n    ) {\n      internalId\n      clientMutationId\n    }\n  }\n": types.SyncPwpSessionDocument,
    "\n  mutation Authenticate($username: String!, $password: String!) {\n    tokenAuth(username: $username, password: $password) {\n      token\n      refreshExpiresIn\n    }\n  }\n": types.AuthenticateDocument,
    "\n  query GetCurrentUser {\n    user {\n      id\n      username\n      email\n      lastName\n      otherNames\n      phone\n      iUser {\n        id\n        language {\n          code\n          name\n        }\n      }\n    }\n  }\n": types.GetCurrentUserDocument,
    "\n  query GetDistrictsSync($after: String, $first: Int!) {\n    locations(type: \"D\", after: $after, first: $first) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          uuid\n          name\n          code\n          parent {\n            id\n          }\n        }\n      }\n    }\n  }\n": types.GetDistrictsSyncDocument,
    "\n  query GetRegionsSync($after: String, $first: Int!) {\n    locations(type: \"R\", after: $after, first: $first) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          uuid\n          name\n          code\n        }\n      }\n    }\n  }\n": types.GetRegionsSyncDocument,
    "\n  query GetLocationGroups($after: String, $first: Int, $villageId: String) {\n    group(\n      isDeleted: false\n      parentLocation: $villageId\n      parentLocationLevel: 3\n      first: $first\n      after: $after\n    ) {\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      edges {\n        node {\n          id\n          uuid\n          code\n          head {\n            firstName\n            lastName\n          }\n          jsonExt\n          groupindividuals(first: 50, isDeleted: false) {\n            edges {\n              node {\n                individual {\n                  uuid\n                  benefitconsumptionSet(first: 50, isDeleted: false) {\n                    edges {\n                      node {\n                        id\n                        uuid\n                        amount\n                        dateDue\n                        status\n                        type\n                        payrollbenefitconsumptionSet(first: 5, isDeleted: false) {\n                          edges {\n                            node {\n                              payroll {\n                                paymentCycle {\n                                  code\n                                  startDate\n                                  endDate\n                                }\n                              }\n                            }\n                          }\n                        }\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetLocationGroupsDocument,
    "\n  query GetVillagesSync($after: String, $first: Int!) {\n    locations(type: \"V\", after: $after, first: $first) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          uuid\n          name\n          code\n          parent {\n            id\n          }\n        }\n      }\n    }\n  }\n": types.GetVillagesSyncDocument,
    "\n  query GetWardsSync($after: String, $first: Int!) {\n    locations(type: \"W\", after: $after, first: $first) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          uuid\n          name\n          code\n          parent {\n            id\n          }\n        }\n      }\n    }\n  }\n": types.GetWardsSyncDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetRegionDistricts($regionId: ID) {\n    locations(type: \"R\", id: $regionId) {\n      edges {\n        node {\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetRegionDistrictsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetRegionsWithDistricts {\n    locations(type: \"R\") {\n      edges {\n        node {\n          id\n          uuid\n          name\n          code\n          type\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetRegionsWithDistrictsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetWardVillages($wardId: ID) {\n    locations(type: \"W\", id: $wardId) {\n      edges {\n        node {\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetWardVillagesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetDistrictWards($districtId: ID) {\n    locations(type: \"D\", id: $districtId) {\n      edges {\n        node {\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n                children {\n                  edges {\n                    node {\n                      id\n                      uuid\n                      name\n                      code\n                      type\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetDistrictWardsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation SyncPaymentAccount(\n    $accountProvider: String\n    $accountNumber: String\n    $accountName: String\n    $householdId: String\n    $clientMutationId: String\n  ) {\n    createTicket(\n      input: {\n        title: $accountProvider\n        category: \"PaymentAccount\"\n        description: $accountName\n        flags: $accountNumber\n        channel: $householdId\n        clientMutationId: $clientMutationId\n      }\n    ) {\n      internalId\n      clientMutationId\n    }\n  }\n"): typeof import('./graphql').SyncPaymentAccountDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation SyncHouseholdChange(\n    $title: String\n    $category: String!\n    $flags: String\n    $channel: String\n    $description: String\n    $clientMutationId: String\n  ) {\n    createTicket(\n      input: {\n        title: $title\n        category: $category\n        flags: $flags\n        channel: $channel\n        description: $description\n        clientMutationId: $clientMutationId\n      }\n    ) {\n      internalId\n      clientMutationId\n    }\n  }\n"): typeof import('./graphql').SyncHouseholdChangeDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateAttendance(\n    $title: String\n    $category: String!\n    $priority: String\n    $incidentDate: Date\n    $flags: String\n    $channel: String\n    $description: String\n    $clientMutationId: String\n  ) {\n    createTicket(\n      input: {\n        title: $title\n        category: $category\n        priority: $priority\n        channel: $channel\n        dateOfIncident: $incidentDate\n        flags: $flags\n        description: $description\n        clientMutationId: $clientMutationId\n      }\n    ) {\n      internalId\n      clientMutationId\n    }\n  }\n"): typeof import('./graphql').CreateAttendanceDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetRegionDistrictsForField($regionId: ID) {\n    locations(type: \"R\", id: $regionId) {\n      edges {\n        node {\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetRegionDistrictsForFieldDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetRegionsWithDistrictsForField {\n    locations(type: \"R\") {\n      edges {\n        node {\n          id\n          uuid\n          name\n          code\n          type\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetRegionsWithDistrictsForFieldDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetWardVillagesForField($wardId: ID) {\n    locations(type: \"W\", id: $wardId) {\n      edges {\n        node {\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetWardVillagesForFieldDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetDistrictWardsForField($districtId: ID) {\n    locations(type: \"D\", id: $districtId) {\n      edges {\n        node {\n          children {\n            edges {\n              node {\n                id\n                uuid\n                name\n                code\n                type\n                children {\n                  edges {\n                    node {\n                      id\n                      uuid\n                      name\n                      code\n                      type\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetDistrictWardsForFieldDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateGrievance(\n    $title: String\n    $category: String!\n    $priority: String\n    $incidentDate: Date\n    $flags: String\n    $channel: String\n    $description: String\n    $clientMutationId: String\n  ) {\n    createTicket(\n      input: {\n        title: $title\n        category: $category\n        priority: $priority\n        channel: $channel\n        dateOfIncident: $incidentDate\n        flags: $flags\n        description: $description\n        clientMutationId: $clientMutationId\n      }\n    ) {\n      internalId\n      clientMutationId\n    }\n  }\n"): typeof import('./graphql').CreateGrievanceDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation SyncPwpSession(\n    $date: String\n    $notes: String\n    $villageId: String\n    $clientMutationId: String\n  ) {\n    createTicket(\n      input: {\n        title: $date\n        category: \"PWP\"\n        description: $notes\n        flags: $villageId\n        clientMutationId: $clientMutationId\n      }\n    ) {\n      internalId\n      clientMutationId\n    }\n  }\n"): typeof import('./graphql').SyncPwpSessionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation Authenticate($username: String!, $password: String!) {\n    tokenAuth(username: $username, password: $password) {\n      token\n      refreshExpiresIn\n    }\n  }\n"): typeof import('./graphql').AuthenticateDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetCurrentUser {\n    user {\n      id\n      username\n      email\n      lastName\n      otherNames\n      phone\n      iUser {\n        id\n        language {\n          code\n          name\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetCurrentUserDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetDistrictsSync($after: String, $first: Int!) {\n    locations(type: \"D\", after: $after, first: $first) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          uuid\n          name\n          code\n          parent {\n            id\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetDistrictsSyncDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetRegionsSync($after: String, $first: Int!) {\n    locations(type: \"R\", after: $after, first: $first) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          uuid\n          name\n          code\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetRegionsSyncDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetLocationGroups($after: String, $first: Int, $villageId: String) {\n    group(\n      isDeleted: false\n      parentLocation: $villageId\n      parentLocationLevel: 3\n      first: $first\n      after: $after\n    ) {\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      edges {\n        node {\n          id\n          uuid\n          code\n          head {\n            firstName\n            lastName\n          }\n          jsonExt\n          groupindividuals(first: 50, isDeleted: false) {\n            edges {\n              node {\n                individual {\n                  uuid\n                  benefitconsumptionSet(first: 50, isDeleted: false) {\n                    edges {\n                      node {\n                        id\n                        uuid\n                        amount\n                        dateDue\n                        status\n                        type\n                        payrollbenefitconsumptionSet(first: 5, isDeleted: false) {\n                          edges {\n                            node {\n                              payroll {\n                                paymentCycle {\n                                  code\n                                  startDate\n                                  endDate\n                                }\n                              }\n                            }\n                          }\n                        }\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetLocationGroupsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetVillagesSync($after: String, $first: Int!) {\n    locations(type: \"V\", after: $after, first: $first) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          uuid\n          name\n          code\n          parent {\n            id\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetVillagesSyncDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetWardsSync($after: String, $first: Int!) {\n    locations(type: \"W\", after: $after, first: $first) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          uuid\n          name\n          code\n          parent {\n            id\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetWardsSyncDocument;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
